# NAME="car"
# USER="root"
# PASSWORD=""
# HOST="localhost"

# NAME = "car"
# USER = "root"
# PASSWORD = "@Mohammad1382"
# HOST = "localhost"
# # HOST = "db"

NAME = "mysql"
USER = "root"
PASSWORD = "BFCiECluC8UY3iRFxK48"
# HOST = "localhost"
HOST = "cardb.caralytix.svc"
