# NAME="car"
# USER="root"
# PASSWORD=""
# HOST="localhost"

# NAME = "car"
# USER = "root"
# PASSWORD = "@Mohammad1382"
# HOST = "localhost"
# # HOST = "db"

NAME = "hamdb"
USER = "hamadmin"
PASSWORD = "v6DT0QRKjIAVpPMh715D"
# HOST = "localhost"
HOST = "caralytix-db-proxysql-svc.caralytix.svc"
