# NAME="car"
# USER="root"
# PASSWORD=""
# HOST="localhost"

# NAME = "car"
# USER = "root"
# PASSWORD = "@Mohammad1382"
# HOST = "localhost"
# # HOST = "db"

NAME = "mysql"
USER = "root"
PASSWORD = "X0q0SpZkPCACDvxvHZBM"
# HOST = "localhost"
HOST = "car-db.caralytix.svc"
