# Generated by Django 5.2 on 2025-04-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField(choices=[(1, 'Khodro45')])),
                ('slug', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
                ('option', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField(null=True)),
                ('mile', models.FloatField(null=True)),
                ('gearbox', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('year', models.CharField(max_length=255, null=True)),
                ('car_specifications', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
