# Generated by Django 4.2.8 on 2025-08-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
                ('option', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField(null=True)),
                ('mile', models.FloatField(null=True)),
                ('gearbox', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('year', models.CharField(max_length=255, null=True)),
                ('car_specifications', models.CharField(max_length=255, null=True)),
                ('body_health', models.CharField(max_length=255, null=True)),
                ('engine_status', models.CharField(max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_At', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='car_specifications',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gearbox',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mile',
        ),
        migrations.RemoveField(
            model_name='client',
            name='model',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='option',
        ),
        migrations.RemoveField(
            model_name='client',
            name='price',
        ),
        migrations.RemoveField(
            model_name='client',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='client',
            name='year',
        ),
        migrations.AlterField(
            model_name='client',
            name='client',
            field=models.IntegerField(choices=[(1, 'Khodro45'), (2, 'Hamrah Mechanic')]),
        ),
    ]
