# Generated by Django 5.2 on 2025-04-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_car_remove_client_car_specifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_health',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
