# Generated by Django 4.2.8 on 2025-08-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_car_body_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
