# Generated by Django 4.2.8 on 2025-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_car_engine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client',
            field=models.IntegerField(choices=[(1, 'Khodro45'), (2, 'Hamrah Mechanic')]),
        ),
    ]
