# Generated by Django 4.2.8 on 2025-08-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_alter_client_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created_At',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
